FROM cgr.dev/chainguard/wolfi-base:latest

# Install necessary dependencies
RUN apk update && apk add \
    git \
    bison \
    make \
    gcc \
    flex \
    sudo \
    python3 \
    py3-pip \
    python3-dev \
    go

# Create a virtual environment
RUN python3 -m venv /venv

# Activate the virtual environment
ENV PATH="/venv/bin:$PATH"

# Install Python dependencies within the virtual environment
RUN pip install rich pygments

# Install gum using go install and GOBIN
RUN GOBIN=/usr/local/bin go install github.com/charmbracelet/gum@latest

# Ensure gum is in the path.
ENV PATH="/usr/local/bin:$PATH"

WORKDIR /app

COPY build-kernel.py /app/

RUN chmod +x /app/build-kernel.py

CMD ["python3", "/app/build-kernel.py"]